### ISSUE TITLE
[1.1-2] Neat turns Botania's (1.8.9 port) particles into bubbles.

### ISSUE THREAD

**Issue by Xiaminou** [Vazkii/Neat#6] opened 2016-01-22 14:59 UTC
Whenever there is an health bar on my screen Botania's particle effects turn into "bubble effects"

Screenshot 1: no health bar
![2016-01-22_15 55 33](https://cloud.githubusercontent.com/assets/8670392/12513977/0bb87b24-c121-11e5-848a-c1c94af9b0be.png)

Screenshot 2: health bar
![2016-01-22_15 55 35](https://cloud.githubusercontent.com/assets/8670392/12513991/209753ee-c121-11e5-91db-c4f1e0111a7a.png)

**Comment by GirafiStudios** [comment] 2016-01-22 15:59
Duplicate of https://github.com/Vazkii/Neat/issues/4

**Comment by Xiaminou** [comment] 2016-01-22 16:12
damn I forgot to check the closed ones, again... (if only github showed all the issues by default...)

**Closed** 2016-02-14 13:12 UTC
